### ISSUE TITLE
Adding types declaration for TS projects.

### ISSUE THREAD

**Issue by Mkaranter** [RickBr0wn/react-uuid#3]
Hey man! Thanks for awesome work.

What are your thoughts of adding file with types declaration. Would accept PR with this?

**Comment by RickBr0wn** [comment]
Hi, sorry for late response, and thank you so much for your comment. I'm a self teaching developer and this is the first contact I've had about my code, it really does mean more than you think, and will inspire me to continue to move forward.

A file with types declaration would be great, I'm sure I'd learn a lot from it's implementation.
Please go ahead 👍🏻
