### ISSUE TITLE
Generated uuids are not always 36 chars long

### ISSUE THREAD

**Issue by pierre-moire** [RickBr0wn/react-uuid#4]
The generated UUIDs should be 36 chars long (32 + 4x "-" ) and it is not always the case.

Could you confirm what seems to be a bug ? I got errors in my application dued to invalid UUIDs

https://codepen.io/pierre-moire/pen/abwKqVo

**Comment by haulin** [comment]
Here's a fixed version:

```js
function uuid() {
  const hashTable = ['a', 'b', 'c', 'd', 'e', 'f', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
  let uuid = [];
  for (let i = 0; i <= 35; i++) {
    if (i === 7 || i === 12 || i === 17 || i === 22) {
      uuid[i] = '-';
    } else {
      uuid[i] = hashTable[Math.floor(Math.random() * (hashTable.length - 1))];
    }
  }
  return uuid.join('');
}
```

**Comment by RickBr0wn** [comment]
Sorry for belated reply. Anyways, dunno if you're still using this package, I do hope so. The problem highlighted has now been completed by #7 .

Many thanks for your input.
